config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'books/index'
  root to: "books#index"
  resources :users, only: :show
  resources :books do
    resources :comments, only: :create
  end
end

app/models/age.rb
class Age < ActiveHash::Base
  self.data = [
    { id: 0, name: '--' },
    { id: 1, name: '10代以下' },
    { id: 2, name: '10代' },
    { id: 3, name: '20代' },
    { id: 4, name: '30代' },
    { id: 5, name: '40代' },
    { id: 6, name: '50代' },
    { id: 7, name: '60代' },
    { id: 8, name: '70代' },
    { id: 9, name: '80代以上' }
  ]
  include ActiveHash::Associations
  has_many :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to       :user
  has_many         :comments
  has_one_attached :image
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :genre
  
  with_options presence: true do
    validates :title
    validates :genre_id, numericality: { other_than: 0 }
    validates :content
    validates :recommend
  end

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :text, presence: true
end

app/models/genre.rb
class Genre < ActiveHash::Base
  self.data = [
    { id: 0, name: '--' },
    { id: 1, name: '文学・評論' },
    { id: 2, name: 'ビジネス・経済' },
    { id: 3, name: '政治・社会' },
    { id: 4, name: '歴史・地理' },
    { id: 5, name: '芸能・エンタメ' },
    { id: 6, name: 'アート・建築・デザイン' },
    { id: 7, name: '思想・宗教' },
    { id: 8, name: '暮らし・健康・料理' },
    { id: 9, name: 'サイエンス・テクノロジー' },
    { id: 10, name: '趣味・娯楽' },
    { id: 11, name: 'スポーツ・アウトドア' },
    { id: 12, name: '音楽' },
    { id: 13, name: '旅行・紀行' },
    { id: 14, name: '絵本・児童書' },
    { id: 15, name: 'コミックス' },
    { id: 16, name: 'その他' }
  ]
  include ActiveHash::Associations
  has_many :books
end

app/models/position.rb
class Position < ActiveHash::Base
  self.data = [
    { id: 0, name: '--' },
    { id: 1, name: '小学生' },
    { id: 2, name: '中学生' },
    { id: 3, name: '高校生' },
    { id: 4, name: '大学生' },
    { id: 5, name: '会社員' },
    { id: 6, name: '自由業' },
    { id: 7, name: 'フリーター' },
    { id: 8, name: 'その他' }
  ]
  include ActiveHash::Associations
  has_many :users
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  with_options presence: true do
    validates :name
    with_options numericality: { other_than: 0 } do
      validates :age_id
      validates :position_id 
    end
  end
  
  has_many :books
  has_many :comments
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :age
  belongs_to :position
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :age_id, :position_id])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:edit, :show]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :move_to_index, only: :edit

  def index
    @books = Book.all
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
    @comments = @book.comments.includes(:user)
  end

  def edit
  end

  def update
    book = Book.find(params[:id])
    if book.update(book_params)
      redirect_to book_path(book.id)
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    if book.destroy
      redirect_to root_path
    end
  end
  
  private

  def book_params
    params.require(:book).permit(:title, :image, :genre_id, :content, :recommend).merge(user_id: current_user.id)
  end

  def set_book
    @book = Book.find(params[:id])
  end

  def move_to_index
    unless user_signed_in? && current_user.id == @book.user_id
      redirect_to action: :index
    end
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to book_path(@comment.book.id)
    else
      @book = @comment.book
      @comments = @book.comments
      render "books/show"
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, book_id: params[:book_id])
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @name = @user.name
    @books = @user.books
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_book.html.erb
<div class="card">
  <%= link_to image_tag(book.image, class: :card__img), book_path(book.id) %>
  <div class="card__body">
    <%= link_to book.title, book_path(book.id), class: :card__title%>
    <p class="card__summary">
      <%= book.genre.name %>
    </p>
    <%= link_to book.user.name, user_path(book.user.id), class: :card__user %>
  </div>
</div>

app/views/books/_form.html.erb
<%= form_with model: @book, local: true do |f|%>
  <div class="field">
    <%= f.label :title, "タイトル" %><br />
    <%= f.text_field :title, id:"prototype_title" %>
  </div>

  <div class="field">
    <%= f.label :image, "画像" %><br />
    <%= f.file_field :image, id:"prototype_image" %>
  </div>
  <div id="image-list"></div>
  <div class="field">
    <%= f.label :genre_id, "ジャンル" %><br />
    <%= f.collection_select(:genre_id, Genre.all, :id, :name, {}, {class:"form__text"}) %>
  </div>

  <div class="field">
    <%= f.label :content, "内容" %><br />
    <%= f.text_area :content, class: :form__text, id:"prototype_concept" %>
  </div>

  <div class="field">
    <%= f.label :recommend, "おすすめポイント" %><br />
    <%= f.text_area :recommend, class: :form__text, id:"prototype_concept" %>
  </div>

  <div class="actions">
    <%= f.submit "保存する", class: :form__btn  %>
  </div>
<% end %>

app/views/books/edit.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">プロトタイプ編集</h2>
      <%= render partial: "form", locals: { book: @book } %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<main class="main">
  <div class="inner">
    <% if user_signed_in? %>
      <div class="greeting">
        <%= "こんにちは、" %>
        <%= link_to current_user.name, user_path(current_user.id), class: :greeting__link%>
        <%= "さん" %>
      </div>
    <% end %>
    <div class="card__wrapper">
      <%= render partial: 'book', collection: @books %>
    </div>
  </div>
</main>

app/views/books/new.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">新規プロトタイプ投稿</h2>
        <%= render partial: "form", locals: { book: @book } %>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<main class="main">
  <div class="inner">
    <div class="prototype__wrapper">
      <p class="prototype__hedding">
        <%= @book.title %>
      </p>
      <%= link_to @book.user.name, user_path(@book.user.id), class: :prototype__user %>
      <% if user_signed_in? && current_user.id == @book.user_id %>
        <div class="prototype__manage">
          <%= link_to "編集する", edit_book_path(@book.id), method: :get, class: :prototype__btn %>
          <%= link_to "削除する", book_path(@book.id), method: :delete, class: :prototype__btn %>
        </div>
      <% end %>
      <div class="prototype__image">
        <%= image_tag @book.image %>
      </div>
      <div class="prototype__body">
        <div class="prototype__detail">
          <p class="detail__title">ジャンル</p>
          <p class="detail__message">
            <%= @book.genre.name %>
          </p>
        </div>
        <div class="prototype__detail">
          <p class="detail__title">内容</p>
          <p class="detail__message">
            <%= @book.content %>
          </p>
        </div>
        <div class="prototype__detail">
          <p class="detail__title">おすすめポイント</p>
          <p class="detail__message">
            <%= @book.recommend %>
          </p>
        </div>
      </div>
      <div class="prototype__comments">
        <% if user_signed_in? %>
          <%= form_with(model: [@book, @comment], local: true) do |f|%>
            <div class="field">
              <%= f.label :text, "コメント" %><br />
              <%= f.text_field :text, id:"comment_text" %>
            </div>
            <div class="actions">
              <%= f.submit "送信する", class: :form__btn  %>
            </div>
          <% end %> 
        <% end %>
        <ul class="comments_lists">
          <% @comments.each do |comment| %>
            <li class="comments_list">
              <%= comment.text %>
              <%= link_to comment.user.name, user_path(comment.user.id), class: :comment_user %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>ShareBook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
  </head>

  <body>
    <header class="header">
      <div class="inner">
        <div class="nav">
          <div class="nav__left">
            <%= link_to "Share Book", root_path %>
          </div>
          <% if user_signed_in? %>
            <div class="nav__right">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: :nav__logout %>
              <%= link_to "新規投稿", new_book_path, class: :nav__btn %>
            </div>
          <% else %>
            <div class="nav__right">
              <%= link_to "ログイン", new_user_session_path, class: :nav__btn %>
              <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
            </div>
          <% end %>
        </div>
      </div>
    </header>
    <%= yield %>
    <footer class="footer">
      <p class="copyright">Copyright © PROTO SPACE All rights reserved.</p>
    </footer>
  </body>
</html>

app/views/users/show.html.erb
<div class="main">
  <div class="inner">
    <div class="user__wrapper">
      <h2 class="page-heading">
        <%="#{@name}さんの情報"%>
      </h2>
      <table class="table">
        <tbody>
          <tr>
            <th class="table__col1">名前</th>
            <td class="table__col2"><%= @user.name %></td>
          </tr>
          <tr>
            <th class="table__col1">年代</th>
            <td class="table__col2"><%= @user.age.name %></td>
          </tr>
          <tr>
            <th class="table__col1">ポジション</th>
            <td class="table__col2"><%=@user.position.name %></td>
          </tr>
        </tbody>
      </table>
      <h2 class="page-heading">
        <%= "#{@name}さんのおすすめBOOK"%>
      </h2>
      <div class="user__card">
        <%= render partial: 'books/book', collection: @books %>
      </div>
    </div>
  </div>
</div>